### ISSUE TITLE
Wire up a testing bench for the motors

### ISSUE THREAD

**Issue by willmarquis** [antoinejulien/Level-US_GRO400_H21#11]

**Comment by antoinejulien** [comment]
There is a problem accessing the motors from the Arduino IDE. They seem to be unpingable. Issue needs to be addressed first before creating the testing code.

**Comment by P-OL** [comment]
Motors :
DH1901002024 - IP: 224
DH1901002009 - IP: 209
DH1901002015 - IP: 215
DH1901002002 - IP: 202
