### ISSUE TITLE
Look up Python struct module for Python/C++ (interface/control) communication

### ISSUE THREAD

**Issue by willmarquis** [antoinejulien/Level-US_GRO400_H21#23]

**Comment by willmarquis** [comment]
Also look at "asyncio subprocess" module to run the C++ program from the python program.

**Comment by willmarquis** [comment]
Article on communication between Arduino and Raspberry Pi

https://roboticsbackend.com/raspberry-pi-arduino-serial-communication/

**Comment by antoinejulien** [comment]
Might not be necessary, will be put in backlog.
